/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DentalService, Review } from "./types";

export const dentalServices: DentalService[] = [
  {
    id: "cosmetic",
    titleEn: "Cosmetic Veneers",
    titleAr: "ابتسامة هوليود والعدسات التجميلية",
    descriptionEn: "Achieve your dream smile with custom premium veneers and lumineers using modern 3D design mapping.",
    descriptionAr: "احصل على ابتسامة أحلامك مع الفينير اللامينيت عالي الجودة والمصمم رقمياً ثلاثي الأبعاد ليناسب ملامحك بدقة.",
    priceEn: "From $350 / tooth",
    priceAr: "تبدأ من 1,300 ريال / سن",
    icon: "Sparkles",
    durationEn: "2 sessions",
    durationAr: "جلستان"
  },
  {
    id: "implants",
    titleEn: "Dental Implants",
    titleAr: "زراعة الأسنان الفورية",
    descriptionEn: "Restore missing teeth permanently with advanced biocompatible implants that feel and function like real teeth.",
    descriptionAr: "استرجع أسنانك المفقودة بشكل دائم مع زراعات حيوية متطورة تمنحك إحساساً ووظيفة كأنها أسنان طبيعية.",
    priceEn: "From $850",
    priceAr: "تبدأ من 3,200 ريال / سن",
    icon: "Activity",
    durationEn: "45 minutes",
    durationAr: "٤٥ دقيقة"
  },
  {
    id: "whitening",
    titleEn: "Laser Teeth Whitening",
    titleAr: "تبييض الأسنان بالليزر",
    descriptionEn: "Brighten your teeth up to 8 shades in a single comfortable session with ultra-safe blue laser activation.",
    descriptionAr: "احصل على بياض ناصع يصل إلى 8 درجات في جلسة واحدة مريحة وآمنة تماماً باستخدام تقنية الليزر الأزرق الحديثة.",
    priceEn: "$199",
    priceAr: "750 ريال",
    icon: "Sun",
    durationEn: "1 hour",
    durationAr: "ساعة واحدة"
  },
  {
    id: "ortho",
    titleEn: "Clear Aligners & Ortho",
    titleAr: "تقويم الأسنان الشفاف والعادي",
    descriptionEn: "Correct your alignment subtly with top-quality clear aligners or highly custom traditional brackets.",
    descriptionAr: "صحّح تراصف وتطابق أسنانك بشكل غير مرئي باستخدام القوالب الشفافة الأحدث أو التقويم التقليدي المتين.",
    priceEn: "From $1,500",
    priceAr: "تبدأ من 5,500 ريال",
    icon: "ShieldCheck",
    durationEn: "Monthly checks",
    durationAr: "متابعة شهرية"
  },
  {
    id: "pediatric",
    titleEn: "Pediatric Dental Care",
    titleAr: "طب أسنان الأطفال الودود",
    descriptionEn: "A fun, friendly, and anxiety-free dental experience for your children, shielding them with fluoride protection.",
    descriptionAr: "تجربة ممتعة وهادئة وخالية من الخوف لأطفالك، مع تطبيق الفلورايد الوقائي وسد الشقوق لحماية أسنانهم مبكراً.",
    priceEn: "$75",
    priceAr: "280 ريال",
    icon: "Smile",
    durationEn: "30 minutes",
    durationAr: "٣٠ دقيقة"
  },
  {
    id: "scaling",
    titleEn: "Scaling & Deep Cleaning",
    titleAr: "تنظيف وتلميع عميق وإزالة الجير",
    descriptionEn: "Remove plaque, deep-set tartar, and tea/coffee stains, leaving your gums clean and refreshed.",
    descriptionAr: "تخلص من الرواسب الجيرية العميقة والتصبغات العنيدة واستعد صحة ونضارة اللثة لتنفس منتعش.",
    priceEn: "$60",
    priceAr: "220 ريال",
    icon: "Droplets",
    durationEn: "40 minutes",
    durationAr: "٤٠ دقيقة"
  }
];

export const initialReviews: Review[] = [
  {
    id: "rev1",
    patientName: "Yousef Al-Harbi",
    rating: 5,
    commentEn: "Dr. Ahmed is incredible! I was terrified of dental implants, but he explained everything and the treatment was absolutely pain-free.",
    commentAr: "الدكتور أحمد رائع جداً! كنت أشعر برعب شديد من عملية زراعة الأسنان، لكنه شرح لي كل التفاصيل والعملية كانت حرفياً بدون أي ألم.",
    date: "2026-05-18"
  },
  {
    id: "rev2",
    patientName: "Sarah Evans",
    rating: 5,
    commentEn: "Beautiful clinic, very clean and state-of-the-art tools. The teeth whitening treatment gave me instant results. Highly recommend!",
    commentAr: "عيادة غاية في الجمال والنظافة، والأجهزة حديثة جداً. جلسة تبييض الأسنان أعطتني نتيجة فورية مذهلة. ممتنة جداً!",
    date: "2026-05-29"
  },
  {
    id: "rev3",
    patientName: "Dr. Adel Al-Masry",
    rating: 5,
    commentEn: "Excellent clinical skills and extremely professional approach. Our family only visits Dr. Ahmed for orthodontics and periodic cleanings.",
    commentAr: "مهارة طبية فائقة وتعامل راقي جداً. عائلتنا تعتمد كلياً على الدكتور أحمد في كل ما يخص تقويم وجراحة الأسنان والتنظيف الدوري.",
    date: "2026-06-02"
  }
];

export const translations = {
  en: {
    clinicName: "Dr. Ahmed Dental Clinic",
    clinicSub: "Crafting Healthy, Confident smiles Every Day",
    navHome: "Home",
    navServices: "Services",
    navDoctor: "Our Doctor",
    navReviews: "Reviews",
    navBook: "Book Appointment",
    heroTitle: "Your Journey to a Perfect Smile Starts Here",
    heroSubtitle: "Experience world-class digital dentistry with Dr. Ahmed and his dedicated team of specialists. Gentle care, premium technology, and a warm atmosphere tailored for you.",
    heroCTA: "Schedule Free Consultation",
    heroCall: "Or Call Us:",
    statsRating: "Clinic Rating",
    statsPatients: "Satisfied Patients",
    statsExperience: "Years Experience",
    statsEquip: "Hi-Tech Treatment Rooms",
    servicesTitle: "Specialized Dental Treatments",
    servicesSubtitle: "We offer comprehensive family and cosmetic dental solutions with high-grade biocompatible materials.",
    price: "Price",
    duration: "Estimated Time",
    bookService: "Book This Treatment",
    drTitle: "Meet Dr. Ahmed",
    drSubtitle: "Lead Dental Surgeon & Implant Specialist",
    drBio1: "Dr. Ahmed is an internationally board-certified consultant in implantology and cosmetic smile design with over 12 years of hands-on clinical experience.",
    drBio2: "He holds a Master's degree in Oral Surgery and is a member of the American Academy of Implant Dentistry. He integrates cutting-edge digital radiography and laser dentistry to offer minimally invasive, zero-anxiety procedures.",
    drCred1: "Master's Degree in Oral Surgery & Implantology",
    drCred2: "Fellow of the International Congress of Oral Implantologists (ICOI)",
    drCred3: "Elite Member of the American Academy of Cosmetic Dentistry (AACD)",
    drCred4: "Pioneer in Anxiety-Free & Computer-Guided Immediate Implants",
    bookTitle: "Book Your Appointment",
    bookSubtitle: "Ready for your healthy new shine? Reserve your convenient time slot instantly.",
    formName: "Full Name",
    formPhone: "Mobile Number",
    formService: "Select Treatment / Consultation",
    formDate: "Select Date",
    formTime: "Select Time Slot",
    formNotes: "Notes / Symptoms (Optional)",
    formSubmit: "Confirm Booking",
    formSubmitting: "Securing your slot...",
    formSuccess: "Appointment Successfully Scheduled!",
    formSuccessSub: "Dr. Ahmed's coordinator will call you back shortly on your phone to confirm your arrival instructions.",
    viewAppointments: "View My Appointments",
    noAppointments: "No current appointments booked on this device.",
    patientName: "Patient Name",
    patientPhone: "Phone",
    treatment: "Treatment",
    status: "Status",
    statusConfirmed: "Confirmed",
    statusPending: "Pending Appointment",
    close: "Close",
    reviewsTitle: "What Our Patients Say",
    reviewsSubtitle: "Real stories and feedback from patients who restored their smiles and oral health with us.",
    addReviewBtn: "Write a Patient Review",
    submitReview: "Submit Patient Review",
    ratingText: "Your Rating:",
    commentTextEn: "Your review (English)*",
    commentTextAr: "Your review (Arabic)*",
    reviewSuccess: "Thank you! Your feedback helps us maintain the highest care standards.",
    contactTitle: "Location & Working Hours",
    workingHours: "Working Hours",
    operatingDays: "Saturday - Thursday",
    operatingHours: "10:00 AM - 9:00 PM",
    operatingFriday: "Friday",
    operatingFridayHours: "Closed (Emergency only)",
    locationLabel: "Our Location",
    address: "Olaya Street, Block B, 2nd Floor, Riyadh, Saudi Arabia",
    footerText: "Dr. Ahmed Dental Clinic © 2026. All rights reserved. Designed to ensure your absolute comfort and security.",
    quickLinks: "Quick Links",
    contactUs: "Direct Contact",
    mapPlaceholder: "Interactive Map Location",
    getDirections: "Get Directions",
    openNow: "Open Now",
    closedNow: "Closed Now"
  },
  ar: {
    clinicName: "عيادة الدكتور أحمد لطب الأسنان",
    clinicSub: "نصنع ابتسامات صحية وواثقة كل يوم",
    navHome: "الرئيسية",
    navServices: "خدماتنا",
    navDoctor: "عن الدكتور",
    navReviews: "آراء المرضى",
    navBook: "حجز موعد",
    heroTitle: "رحلتك نحو ابتسامة مثالية تبدأ من هنا",
    heroSubtitle: "عش تجربة طب الأسنان الرقمي بمستويات عالمية مع الدكتور أحمد وفريقه المتخصص. رعاية متناهية اللطف، أحدث التقنيات الطبية، وأجواء دافئة تم تصميمها بالكامل لأجلك.",
    heroCTA: "احجز استشارة مجانية الآن",
    heroCall: "أو اتصل بنا مباشرة:",
    statsRating: "تقييم العيادة",
    statsPatients: "مريض سعيد نال الشفاء",
    statsExperience: "سنة من الخبرة والتميز",
    statsEquip: "غرف علاجية رقمية فائقة التجهيز",
    servicesTitle: "تخصصاتنا الاستثنائية",
    servicesSubtitle: "نقدم حلولاً متكاملة وتجميلية لجميع الفئات مستعينين بأفضل المواد الحيوية المتوافقة عالمياً.",
    price: "التكلفة",
    duration: "الوقت المقدر",
    bookService: "احجز هذا الإجراء",
    drTitle: "تعرف على الدكتور أحمد",
    drSubtitle: "استشاري جراحة الأسنان وزراعتها وتجميلها",
    drBio1: "الدكتور أحمد استشاري معتمد دولياً في زراعة الأسنان وتصميم الابتسامة الرقمية (Smile Design)، بخبرة سريرية لـأكثر من 12 عاماً.",
    drBio2: "حاصل على الماجستير في جراحة الفم وزراعة الأسنان، وعضو الجمعية الأمريكية لزراعة الأسنان. يدمج بين التصوير الرقمي ثلاثي الأبعاد وعلاجات الليزر لمنحك إجراءات خالية تماماً من الخوف وبأقل تدخل جراحي ممكن.",
    drCred1: "ماجستير جراحة الفم واللثة وزراعة الأسنان الحديثة",
    drCred2: "زميل المؤتمر الدولي لزراعة الأسنان (ICOI)",
    drCred3: "عضو متميز في الأكاديمية الأمريكية لتجميل الأسنان (AACD)",
    drCred4: "رائد تقنيات الزراعة الفورية الموجهة بالكمبيوتر وبدون ألم",
    bookTitle: "احجز موعد مراجعتك",
    bookSubtitle: "مستعد للحصول على لمعان أسنان صحي جديد؟ احجز فترتك المفضلة على الفور بمرونة تامة.",
    formName: "الاسم الكامل",
    formPhone: "رقم الجوال",
    formService: "اختر العيادة أو نوع الإجراء",
    formDate: "اختر التاريخ",
    formTime: "اختر الفترة الزمنية",
    formNotes: "ملاحظات أو أعراض تشكو منها (اختياري)",
    formSubmit: "تأكيد الحجز الفوري",
    formSubmitting: "جاري حجز موعدك...",
    formSuccess: "تم تسجيل حجزك بنجاح!",
    formSuccessSub: "سيقوم منسق عيادة الدكتور أحمد بالاتصال بك على جوالك لتأكيد الموعد وإرسال لوكيشن العيادة بدقة وإرشادات الحضور.",
    viewAppointments: "عرض حجوزاتي الحالية",
    noAppointments: "لا توجد حجوزات نشطة مسجلة على هذا المتصفح.",
    patientName: "اسم المريض",
    patientPhone: "الجوال",
    treatment: "الإجراء المطلوب",
    status: "حالة الحجز",
    statusConfirmed: "مؤكد",
    statusPending: "بانتظار التأكيد الهاتفي",
    close: "إغلاق",
    reviewsTitle: "ماذا يقول شركاء ابتسامتنا؟",
    reviewsSubtitle: "قصص وشهادات واقعية لمرضى استعادوا ثقتهم اللامعة وصحة أسنانهم بعنايتنا الخاصة.",
    addReviewBtn: "اضف تقييمك الخاص",
    submitReview: "إرسال تقييمك الطبي",
    ratingText: "تقييمك الطبي:",
    commentTextEn: "ملاحظاتك بالإنجليزية*",
    commentTextAr: "رأيك وتجربتك بالتفصيل (بالعربية)*",
    reviewSuccess: "شكراً لك! تقييمك القيم يساعدنا في الحفاظ على ريادة الرعاية الطبية ولطف المعاملة.",
    contactTitle: "الموقع الجغرافي وساعات العمل",
    workingHours: "ساعات العمل الرسمية",
    operatingDays: "السبت - الخميس",
    operatingHours: "10:00 صباحاً - 9:00 مساءً",
    operatingFriday: "الجمعة",
    operatingFridayHours: "مغلق (للحالات الإسعافية الطارئة فقط)",
    locationLabel: "عنوان العيادة الجغرافي",
    address: "شارع العليا العام، مجمع ب، الطابق الثاني، الرياض، المملكة العربية السعودية",
    footerText: "عيادة الدكتور أحمد لطب وزراعة الأسنان © 2026. جميع الحقوق محفوظة لضمان أقصى درجات راحتك وأمانك.",
    quickLinks: "روابط سريعة",
    contactUs: "التواصل المباشر",
    mapPlaceholder: "موقع العيادة التفاعلي على الخريطة",
    getDirections: "الحصول على الاتجاهات",
    openNow: "مفتوح الآن لعلاجكم",
    closedNow: "مغلق حالياً"
  }
};

export const timeSlots = [
  "10:00 AM - 11:00 AM",
  "11:00 AM - 12:00 PM",
  "12:00 PM - 01:00 PM",
  "01:00 PM - 02:00 PM",
  "04:00 PM - 05:00 PM",
  "05:00 PM - 06:00 PM",
  "06:00 PM - 07:00 PM",
  "07:00 PM - 08:00 PM",
  "08:00 PM - 09:00 PM"
];
